import type { Metadata } from "next";
import "./globals.css";
import { Recursive } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";
import Providers from "@/components/Providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const recursive = Recursive({ subsets: ["latin","latin-ext"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${recursive} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <Providers>{children}</Providers>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
